# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html


## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [14]:
arr=np.random.uniform(0,20,(4, 7))
arr


array([[ 3.69010345, 13.76177989, 12.04548394,  9.55936441, 10.14552514,
        11.65640817,  1.78880123],
       [19.58474008,  1.60713775, 10.83887025,  7.50435584, 11.36320771,
        18.12984346,  5.17141478],
       [ 3.52830341,  4.15662501,  0.11946758,  6.93692638,  2.14070134,
        15.16997802, 18.94828324],
       [ 5.70554453,  3.91901215, 16.66773509, 15.88148384,  4.55441427,
         6.34963823, 17.61856754]])

In [23]:
(arr-arr.min()) / (arr.max()-arr.min())

array([[0.18343621, 0.70085391, 0.61268171, 0.48496094, 0.51507409,
        0.59269351, 0.08575958],
       [1.        , 0.07642689, 0.55069369, 0.37938787, 0.57763076,
        0.92525681, 0.25953642],
       [0.17512397, 0.20740308, 0.        , 0.35023701, 0.10383794,
        0.77319803, 0.96730296],
       [0.28697656, 0.19519606, 0.85014312, 0.80975061, 0.22783892,
        0.32006594, 0.89899075]])

In [15]:
arr.min()

0.11946758262192159

In [16]:
arr.max()

19.584740081381366

In [18]:
x=arr.max()-arr.min()
x

19.465272498759443

In [19]:
y=(arr - arr.min())/x
y

array([[0.18343621, 0.70085391, 0.61268171, 0.48496094, 0.51507409,
        0.59269351, 0.08575958],
       [1.        , 0.07642689, 0.55069369, 0.37938787, 0.57763076,
        0.92525681, 0.25953642],
       [0.17512397, 0.20740308, 0.        , 0.35023701, 0.10383794,
        0.77319803, 0.96730296],
       [0.28697656, 0.19519606, 0.85014312, 0.80975061, 0.22783892,
        0.32006594, 0.89899075]])

In [22]:
a=arr/x
a
b=arr.min()/x
b
c=a-b
c

array([[0.18343621, 0.70085391, 0.61268171, 0.48496094, 0.51507409,
        0.59269351, 0.08575958],
       [1.        , 0.07642689, 0.55069369, 0.37938787, 0.57763076,
        0.92525681, 0.25953642],
       [0.17512397, 0.20740308, 0.        , 0.35023701, 0.10383794,
        0.77319803, 0.96730296],
       [0.28697656, 0.19519606, 0.85014312, 0.80975061, 0.22783892,
        0.32006594, 0.89899075]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [25]:
arr=np.random.randint(0,10, size=(8,10))
arr

array([[9, 9, 3, 6, 7, 4, 4, 0, 7, 3],
       [3, 7, 1, 6, 0, 4, 4, 0, 1, 9],
       [8, 2, 4, 2, 0, 0, 5, 1, 4, 7],
       [2, 5, 3, 3, 9, 8, 8, 8, 9, 5],
       [6, 6, 3, 0, 7, 0, 8, 6, 4, 0],
       [0, 4, 2, 6, 9, 1, 6, 4, 2, 0],
       [1, 5, 1, 6, 7, 4, 1, 1, 3, 7],
       [3, 9, 8, 6, 8, 1, 9, 0, 9, 2]])

In [38]:
ind = (arr.sum(axis=1).argmin())
ind
print(f"Строка: {ind+1}")
print(arr[ind])

Строка: 3
[8 2 4 2 0 0 5 1 4 7]


In [36]:
min, max, sum
arr.min(),arr.max(), arr.sum()

(0, 9, 345)

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [42]:
x=np.random.uniform(0,10, (1,2))
y=np.random.uniform(0,10, (1,2))
c = np.linalg.norm(x-y)
c

3.7716611025092432

In [43]:
print(np.sqrt(np.sum((x-y)**2)))

3.7716611025092432


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [48]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B= np. array ([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])
A1=np.linalg.inv(A)
B1=np.linalg.inv(B)
X=A1@(-C)@B1
X

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [2]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [3]:
arr = np.loadtxt('data/minutes_n_ingredients.csv',dtype=int, delimiter=",", skiprows=1)
arr[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [25]:
for i in range(2):
    print(f"""Столбец #{i+1}
    Среднее сзанчение: {np.mean(arr[:, i+1])}
    Среднее сзанчение: {np.min(arr[:, i+1])}
    Среднее сзанчение: {np.max(arr[:, i+1])}
    Среднее сзанчение: {np.median(arr[:, i+1])}
    """)

Столбец #1
    Среднее сзанчение: 21601.00169
    Среднее сзанчение: 0
    Среднее сзанчение: 2147483647
    Среднее сзанчение: 40.0
    
Столбец #2
    Среднее сзанчение: 9.05528
    Среднее сзанчение: 1
    Среднее сзанчение: 39
    Среднее сзанчение: 9.0
    


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [14]:
q = 0.75
x = arr[:, 1] <= np.quantile(arr[:, 1], q)
arr[x]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [15]:
result = np.sum(arr[:, 1] == 0)
result

479

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [17]:
uniq_recipes = np.unique(arr, axis=0)
uniq_recipes.shape

(100000, 3)

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [19]:
unique, counts = np.unique(arr[:, 2], return_counts=True)
print(f"Всего уникальных: {len(unique)}")
dict(zip(counts,unique))

Всего уникальных: 37


{13: 1,
 926: 2,
 2895: 3,
 5515: 4,
 7913: 5,
 9376: 6,
 10628: 7,
 10951: 8,
 10585: 9,
 9591: 10,
 8297: 11,
 6605: 12,
 4997: 13,
 3663: 14,
 2595: 15,
 1767: 16,
 1246: 17,
 790: 18,
 573: 19,
 376: 20,
 217: 21,
 161: 22,
 105: 23,
 69: 24,
 50: 25,
 28: 26,
 16: 28,
 12: 30,
 3: 35,
 1: 39,
 2: 33}

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [20]:
len_less_5 = arr[arr[:, 2] < 6]
len_less_5

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [24]:
arrcopy = arr.copy()
mask = arrcopy[:, 1] == 0
arrcopy[:, 1][mask] = 1
x = (arrcopy[:,2]/(arrcopy[:,1]))
print(f"max: {np.max(x)}")

max: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [40]:
print(arr[np.random.randint(len(arr), size=10)])

[[ 61043     60      6]
 [176015     25     10]
 [260167    860     11]
 [278786     45     12]
 [287536    150     10]
 [104529     75     12]
 [368368    485      5]
 [ 76906      4      3]
 [289232     24      9]
 [147385     90     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [47]:
meann = np.mean(arr[:, 2])
arrayy = arr[arr[:, 2] < meann]
perc = (len(arrayy)*100/len(arr))
print(perc)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.